UI/Pages/Enquiry/Build/AdditionalInformation.cshtml.cs
using Application.Common.Interfaces;
using Application.Common.Models;
using Application.Common.Models.Enquiry.Build;

namespace UI.Pages.Enquiry.Build;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
public class AdditionalInformation : PageModel
{
    private readonly ISessionService _sessionService;

    public AdditionalInformation(ISessionService sessionService)
    {
        _sessionService = sessionService;
    }

    [BindProperty] public AdditionalInformationModel Data { get; set; } = new();

    public async Task<IActionResult> OnGetAsync(AdditionalInformationModel data)
    {
        if (!await _sessionService.SessionDataExistsAsync())
            return RedirectToPage("/Session/Timeout");

        Data = data;

        Data.AdditionalInformation = await _sessionService.RetrieveDataByKeyAsync(SessionKeyConstants.EnquiryAdditionalInformation);

        ModelState.Clear();

        return Page();
    }

    public async Task<IActionResult> OnPostAsync(AdditionalInformationModel data)
    {
        if (!await _sessionService.SessionDataExistsAsync())
            return RedirectToPage("/Session/Timeout");

        Data = data;
        if (ModelState.IsValid)
        {
            await _sessionService.AddOrUpdateDataAsync(SessionKeyConstants.EnquiryAdditionalInformation,
                string.IsNullOrWhiteSpace(data.AdditionalInformation) ? string.Empty : data.AdditionalInformation);

            return RedirectToPage(nameof(CheckYourAnswers), new SearchModel(data));
        }

        return Page();
    }
}

UI/Pages/Enquiry/Build/CheckYourAnswers.cshtml.cs
using Application.Commands.Enquiry.Build;
using Application.Common.Interfaces;
using Application.Common.Models;
using Application.Common.Models.Enquiry.Build;
using Domain.Exceptions;
using Infrastructure.Configuration;
using Microsoft.Extensions.Options;

namespace UI.Pages.Enquiry.Build;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
public class CheckYourAnswers : PageModel
{
    private const string EnquirySubmissionConfirmationModelKey = "EnquirySubmissionConfirmationModel";

    private readonly IMediator _mediator;
    private readonly ISessionService _sessionService;
    private readonly IHostEnvironment _hostEnvironment;
    private readonly FeatureFlags _featureFlagsConfig;
    private readonly ILogger<CheckYourAnswers> _logger;

    public CheckYourAnswers(IMediator mediator, ISessionService sessionService, IHostEnvironment hostEnvironment,
        IOptions<FeatureFlags> featureFlagsConfig, ILogger<CheckYourAnswers> logger)
    {
        _mediator = mediator;
        _sessionService = sessionService;
        _hostEnvironment = hostEnvironment;
        _featureFlagsConfig = featureFlagsConfig.Value;
        _logger = logger;
    }

    [BindProperty] public CheckYourAnswersModel Data { get; set; } = new();

    public async Task<IActionResult> OnGetAsync(CheckYourAnswersModel data)
    {
        if (!await _sessionService.SessionDataExistsAsync())
            return RedirectToPage("/Session/Timeout");

        Data = data;

        await _sessionService.AddOrUpdateDataAsync(SessionKeyConstants.EmailVerificationPasscode, string.Empty);
        await _sessionService.AddOrUpdateDataAsync(SessionKeyConstants.EmailToBeVerified, string.Empty);

        var sessionValues = await _sessionService.RetrieveDataAsync();

        if (sessionValues != null)
        {
            foreach (var sessionValue in sessionValues)
            {
                ParseSessionValue(sessionValue.Key, sessionValue.Value);
            }
        }

        Data.KeyStageSubjects = GetKeyStageSubject(Data.Subjects);
        Data.HasKeyStageSubjects = Data.KeyStageSubjects.Any();

        var postcodeAndSchoolValid = false;
        if (!string.IsNullOrWhiteSpace(Data.Postcode) && Data.SchoolId.HasValue)
        {
            var locationResult = await _mediator.Send(new GetSearchLocationQuery(Data.Postcode));

            if (locationResult.TryValidate(true).IsSuccess)
            {
                Data.LocalAuthorityDistrictName = locationResult!.LocalAuthorityDistrict;

                var school = locationResult!.Schools!.FirstOrDefault(x => x.Id == Data.SchoolId.Value);

                if (school != null)
                {
                    Data.SchoolDetails = $"{school.EstablishmentName}, {Data.Postcode}";
                    Data.SchoolUrn = school.Urn;
                    postcodeAndSchoolValid = true;
                }
            }
        }

        if (!postcodeAndSchoolValid)
        {
            Data.LocalAuthorityDistrictName = null;
            Data.SchoolId = null;
            Data.SchoolDetails = null;
            Data.SchoolUrn = null;
            Data.Postcode = null;
        }

        HttpContext.AddLadNameToAnalytics<CheckYourAnswers>(Data.LocalAuthorityDistrictName);

        ModelState.Clear();

        return Page();
    }

    public async Task<IActionResult> OnPostAsync()
    {
        if (!_featureFlagsConfig.EnquiryBuilder)
            throw new InvalidOperationException("User is trying to submit an enquiry when the feature is disabled");

        var isDuplicateFormPost = await _sessionService.IsDuplicateFormPostAsync();

        if (!await _sessionService.SessionDataExistsAsync() && !isDuplicateFormPost)
            return RedirectToPage("/Session/Timeout");

        Data.KeyStageSubjects = GetKeyStageSubject(Data.Subjects);

        if (!ModelState.IsValid) return Page();

        if (!isDuplicateFormPost)
        {
            await _sessionService.StartFormPostProcessingAsync();
        }

        var searchResultsData = new GetSearchResultsQuery(Data);
        var searchResults = await _mediator.Send(searchResultsData);
        Data = Data with { TuitionPartnersForEnquiry = searchResults.Results };

        Data.BaseServiceUrl = Request.GetBaseServiceUrl();

        var submittedConfirmationModel = new SubmittedConfirmationModel();

        if (!isDuplicateFormPost)
        {
            var command = new AddEnquiryCommand()
            {
                Data = Data
            };

            try
            {
                submittedConfirmationModel = await _mediator.Send(command);
            }
            catch (EmailSendException)
            {
                submittedConfirmationModel.HadEmailSendException = true;
            }
            await _sessionService.SetFormPostResponseAsync(submittedConfirmationModel, EnquirySubmissionConfirmationModelKey);
        }
        else
        {
            submittedConfirmationModel = await _sessionService.GetPreviousFormPostResponseAsync<SubmittedConfirmationModel>(EnquirySubmissionConfirmationModelKey);
        }

        if (submittedConfirmationModel.HadEmailSendException)
        {
            Data.From = ReferrerList.CheckYourAnswers;

            await _sessionService.AddOrUpdateDataAsync(SessionKeyConstants.EnquirerEmailErrorMessage, Constants.StringConstants.EmailErrorMessage);

            return RedirectToPage(nameof(EnquirerEmail), new SearchModel(Data));
        }

        await _sessionService.DeleteDataAsync();

        var submittedConfirmationModelRouteData = new SubmittedConfirmationModel(Data)
        {
            SupportReferenceNumber = submittedConfirmationModel.SupportReferenceNumber,
            LocalAuthorityDistrictName = Data.LocalAuthorityDistrictName
        };

        if (!_hostEnvironment.IsProduction())
        {
            submittedConfirmationModelRouteData.EnquirerMagicLink = submittedConfirmationModel.EnquirerMagicLink;

            submittedConfirmationModelRouteData.TuitionPartnerMagicLinksCount = submittedConfirmationModel.TuitionPartnerMagicLinksCount;

            var tuitionPartnerMagicLinksToDisplayForTesting = submittedConfirmationModel.TuitionPartnerMagicLinks.Take(10)
                .OrderBy(x => x.Email).ToList();

            submittedConfirmationModelRouteData.TuitionPartnerMagicLinks = tuitionPartnerMagicLinksToDisplayForTesting;
        }

        HttpContext.AddHasSENDQuestionToAnalytics<CheckYourAnswers>((!string.IsNullOrWhiteSpace(Data.SENDRequirements)).ToString());
        HttpContext.AddHasAdditionalInformationQuestionToAnalytics<CheckYourAnswers>((!string.IsNullOrWhiteSpace(Data.AdditionalInformation)).ToString());
        HttpContext.AddTuitionPartnerNameCsvAnalytics<CheckYourAnswers>(string.Join(",", Data.TuitionPartnersForEnquiry!.Results.Select(x => x.Name)));
        HttpContext.AddLadNameToAnalytics<CheckYourAnswers>(Data.LocalAuthorityDistrictName);
        HttpContext.AddSchoolUrnToAnalytics<CheckYourAnswers>(Data.SchoolUrn!.Value);
        HttpContext.AddEnquirySupportReferenceNumberToAnalytics<CheckYourAnswers>(submittedConfirmationModel.SupportReferenceNumber);

        return RedirectToPage(nameof(SubmittedConfirmation), submittedConfirmationModelRouteData);
    }

    private void ParseSessionValue(string key, string value)
    {
        switch (key)
        {
            case var k when k.Equals(SessionKeyConstants.EnquiryNumberOfPupils, StringComparison.OrdinalIgnoreCase):
                Data.TutoringLogisticsDetailsModel.NumberOfPupils = value;
                break;

            case var k when k.Equals(SessionKeyConstants.EnquiryStartDate, StringComparison.OrdinalIgnoreCase):
                Data.TutoringLogisticsDetailsModel.StartDate = value;
                break;

            case var k when k.Equals(SessionKeyConstants.EnquiryTuitionDuration, StringComparison.OrdinalIgnoreCase):
                Data.TutoringLogisticsDetailsModel.TuitionDuration = value;
                break;

            case var k when k.Equals(SessionKeyConstants.EnquiryTimeOfDay, StringComparison.OrdinalIgnoreCase):
                Data.TutoringLogisticsDetailsModel.TimeOfDay = value;
                break;

            case var k when k.Equals(SessionKeyConstants.EnquirySENDRequirements, StringComparison.OrdinalIgnoreCase):
                Data.SENDRequirements = value;
                break;

            case var k when k.Equals(SessionKeyConstants.EnquiryAdditionalInformation, StringComparison.OrdinalIgnoreCase):
                Data.AdditionalInformation = value;
                break;

            case var k when k.Equals(SessionKeyConstants.EnquirySchoolId, StringComparison.OrdinalIgnoreCase):
                Data.SchoolId = string.IsNullOrEmpty(value) ? null : int.Parse(value);
                break;

            case var k when k.Equals(SessionKeyConstants.EnquirerEmail, StringComparison.OrdinalIgnoreCase):
                Data.Email = value;
                break;
        }
    }
    private static Dictionary<KeyStage, List<Subject>> GetKeyStageSubject(string[]? subjects)
    {
        if (subjects == null || subjects.Length == 0)
            return new Dictionary<KeyStage, List<Subject>>();

        var keyStageSubjects = subjects.ParseKeyStageSubjects() ?? Array.Empty<KeyStageSubject>();

        var allSubjects = Enum.GetValues(typeof(Subject)).Cast<Subject>();

        return keyStageSubjects
            .GroupBy(x => x.KeyStage)
            .OrderBy(x => x.Key.DisplayName())
            .Select(x => new
            {
                x.Key,
                Values = x
                .Select(y => allSubjects
                .FirstOrDefault(allsub => allsub.ToString().ToSeoUrl() == y.Subject.ToSeoUrl()))
                .Where(x => x != Subject.Unspecified)
            })
            .Where(x => x.Values.Any())
            .ToDictionary(x => x.Key, x => x.Values.ToList());
    }
}

UI/Pages/Enquiry/Build/EmailVerification.cshtml.cs
using Application.Commands.Enquiry.Build;
using Application.Common.Interfaces;
using Application.Common.Models;
using Application.Common.Models.Enquiry.Build;
using Domain.Exceptions;

namespace UI.Pages.Enquiry.Build;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
public class EmailVerification : PageModel
{
    private readonly IMediator _mediator;
    private readonly ISessionService _sessionService;
    private readonly IHostEnvironment _hostEnvironment;

    public EmailVerification(IMediator mediator,
        ISessionService sessionService,
        IHostEnvironment hostEnvironment)
    {
        _mediator = mediator;
        _sessionService = sessionService;
        _hostEnvironment = hostEnvironment;
    }
    [BindProperty] public EmailVerificationModel Data { get; set; } = new();

    public async Task<IActionResult> OnGetAsync(EmailVerificationModel data)
    {
        var emailToBeVerified = await _sessionService.RetrieveDataByKeyAsync(SessionKeyConstants.EmailToBeVerified);

        if (string.IsNullOrWhiteSpace(emailToBeVerified))
            return RedirectToPage("/Session/Timeout");

        Data = data;

        Data.Email = emailToBeVerified;

        if (!_hostEnvironment.IsProduction())
        {
            data.PasscodeForTesting = await _sessionService.RetrieveDataByKeyAsync(SessionKeyConstants.EmailVerificationPasscode);
        }

        ModelState.Clear();

        return Page();
    }
    public async Task<IActionResult> OnPostAsync(EmailVerificationModel data)
    {
        var passcode = await _sessionService.RetrieveDataByKeyAsync(SessionKeyConstants.EmailVerificationPasscode);
        var emailToBeVerified = await _sessionService.RetrieveDataByKeyAsync(SessionKeyConstants.EmailToBeVerified);

        if (string.IsNullOrWhiteSpace(passcode) || string.IsNullOrWhiteSpace(emailToBeVerified))
            return RedirectToPage("/Session/Timeout");

        Data = data;
        if (ModelState.IsValid)
        {
            if (!passcode.Equals(data.Passcode))
            {
                ModelState.AddModelError("Data.Passcode", "Enter a correct passcode");
                return Page();
            }

            await _sessionService.AddOrUpdateDataAsync(SessionKeyConstants.EnquirerEmail, emailToBeVerified);

            await _sessionService.AddOrUpdateDataAsync(SessionKeyConstants.EmailVerificationPasscode, string.Empty);
            await _sessionService.AddOrUpdateDataAsync(SessionKeyConstants.EmailToBeVerified, string.Empty);

            if (data.From == ReferrerList.CheckYourAnswers)
            {
                return RedirectToPage(nameof(CheckYourAnswers), new SearchModel(data));
            }

            return RedirectToPage(nameof(TutoringLogistics), new SearchModel(data));
        }

        return Page();
    }

    public async Task<IActionResult> OnPostNewPasscodeAsync(EmailVerificationModel data)
    {
        var emailToBeVerified = await _sessionService.RetrieveDataByKeyAsync(SessionKeyConstants.EmailToBeVerified);

        if (string.IsNullOrWhiteSpace(emailToBeVerified))
            return RedirectToPage("/Session/Timeout");

        var sendEmailVerificationCommand = new SendEmailVerificationCommand()
        {
            Email = emailToBeVerified,
            PasscodeLength = Constants.IntegerConstants.EmailVerificationPasscodeLength,
            SessionTimeoutMinutes = Constants.DoubleConstants.SessionTimeoutInMinutes,
            BaseServiceUrl = Request.GetBaseServiceUrl()
        };

        int? passcode;

        try
        {
            passcode = await _mediator.Send(sendEmailVerificationCommand);
        }
        catch (EmailSendException)
        {
            await _sessionService.AddOrUpdateDataAsync(SessionKeyConstants.EnquirerEmailErrorMessage, Constants.StringConstants.EmailErrorMessage);

            return RedirectToPage(nameof(EnquirerEmail), new SearchModel(Data));
        }

        await _sessionService.AddOrUpdateDataAsync(SessionKeyConstants.EmailVerificationPasscode, passcode.Value.ToString());

        data.NewPasscodeSentAt = DateTime.UtcNow.ToLocalDateTime().ToString("h:mmtt");
        data.Passcode = null;
        data.PasscodeForTesting = null;
        data.Email = null;

        return RedirectToPage(data);
    }
}

UI/Pages/Enquiry/Build/EnquiryQuestion.cshtml.cs
using Application.Common.Interfaces;
using Application.Common.Models;
using Application.Common.Models.Enquiry.Build;

namespace UI.Pages.Enquiry.Build;

public class EnquiryQuestion : PageModel
{
    private readonly ISessionService _sessionService;

    public EnquiryQuestion(ISessionService sessionService)
    {
        _sessionService = sessionService;
    }

    [BindProperty(SupportsGet = true)] public EnquiryQuestionModel Data { get; set; } = new();

    public async Task<IActionResult> OnGet(EnquiryQuestionModel data)
    {
        if (!await _sessionService.SessionDataExistsAsync())
            return RedirectToPage("/Session/Timeout");

        Data = data;

        Data.EnquiryText = await _sessionService.RetrieveDataAsync(StringConstants.EnquiryText);

        ModelState.Clear();

        return Page();
    }

    public async Task<IActionResult> OnGetSubmit(EnquiryQuestionModel data)
    {
        if (!await _sessionService.SessionDataExistsAsync())
            return RedirectToPage("/Session/Timeout");

        Data = data;

        if (ModelState.IsValid)
        {
            await _sessionService.AddOrUpdateDataAsync(StringConstants.EnquiryText, data.EnquiryText!);

            return RedirectToPage(nameof(CheckYourAnswers), new SearchModel(data));
        }

        return Page();
    }
}

UI/Pages/Enquiry/Build/AdditionalInformation.cshtml
@page
@using Application.Constants
@model UI.Pages.Enquiry.Build.AdditionalInformation
@using GovUk.Frontend.AspNetCore.TagHelpers
@{
  var backLink = Model.Data.From == ReferrerList.CheckYourAnswers ? "/enquiry/build/check-your-answers" : "/enquiry/build/send-requirements";
  ViewData["Title"] = "Other tuition requirements";
  ViewData["BackLinkHref"] = $"{backLink}?{Model.Data.ToQueryString()}";
}

<form method="post">
  <span class="govuk-caption-l">Create your tuition enquiry</span>
  <h1 class="govuk-heading-l">Other tuition requirements</h1>
  <p class="govuk-body">You should list other requirements you want tuition partners to consider. Here are some examples:</p>
  <ul class="govuk-list govuk-list--bullet govuk-!-margin-left-4">
    <li>discuss your budget or price range</li>
    <li>describe particular tuition needs within subjects such as phonics, reading or writing within English</li>
    <li>let tuition partners know if your school is in a potentially hard to reach area for face-to-face tuition</li>
  </ul>
  <partial name="_PIIWarning" />
  <govuk-character-count asp-for="Data.AdditionalInformation" threshold="@IntegerConstants.LargeTextAreaMaxCharacterThreshold" rows="12" max-length="@IntegerConstants.LargeTextAreaMaxCharacterSize">
    <govuk-character-count-label class="govuk-label--m">
      Is there anything else you want tuition partners to consider? (optional)
    </govuk-character-count-label>
  </govuk-character-count>
  <partial name="_SearchModelHiddenInputs" model="@Model.Data" />
  <input type="hidden" name="handler" value="Submit" />
  <govuk-button prevent-double-click="true" type="submit" data-testid="call-to-action">Continue</govuk-button>
</form>

UI/Pages/Enquiry/Build/ConfirmSchool.cshtml
@page
@model ConfirmSchool
@using GovUk.Frontend.AspNetCore.TagHelpers
@{
  var title = Model.Data.HasSingleSchool ? "Confirm this is the school you need tuition for" : "Confirm which school you need tuition for";
  var hintText = "We need to check which school you work for, and that you’re enquiring about tuition services on their behalf. This information won’t be shared with tuition partners.";
  var backLink = Model.FromSchoolPostcode ? "/enquiry/build/school-postcode" : "/enquiry/build/guidance";
  var backQueryString = Model.FromSchoolPostcode ? Model.Data.ToQueryString(new Dictionary<string, string>() { { "SchoolPostcode", Model.Data.SchoolPostcode! } }) : Model.Data.ToQueryString();
  ViewData["Title"] = title;
  ViewData["BackLinkHref"] = $"{backLink}?{backQueryString}";
}

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <form method="post">
      @if(Model.Data.HasSingleSchool)
      {
        <h1 class="govuk-heading-l">@title</h1>
        <p class="govuk-body" show-if="!Model.FromSchoolPostcode">@hintText</p>

        <partial name="_SchoolDetails" model="@Model.Data.Schools.First()" />

        <govuk-radios asp-for="Data.ConfirmedIsSchool">
          <govuk-radios-fieldset>
            <govuk-radios-fieldset-legend>
              <h2 class="govuk-heading-m">Is this your school?</h2>
            </govuk-radios-fieldset-legend>
            <govuk-radios-item value="@true">
              Yes
            </govuk-radios-item>
            <govuk-radios-item value="@false">
              No, I need to choose another school
            </govuk-radios-item>
          </govuk-radios-fieldset>
        </govuk-radios>
      }
      else
      {
        <govuk-radios asp-for="Data.SchoolId">
          <govuk-radios-fieldset>
            <govuk-radios-fieldset-legend is-page-heading="true" class="govuk-fieldset__legend--l">
              @title
            </govuk-radios-fieldset-legend>
            <govuk-radios-hint show-if="!Model.FromSchoolPostcode">
              @hintText
            </govuk-radios-hint>
            @foreach (var school in Model.Data.Schools)
            {
              <govuk-radios-item value="@school.Id">
                <h2 class="govuk-heading-m">@school.Urn, @school.EstablishmentName, @school.Postcode</h2>
                <govuk-radios-item-conditional>
                  <partial name="_SchoolDetails" model="@school" />
                </govuk-radios-item-conditional>
              </govuk-radios-item>
            }
          </govuk-radios-fieldset>
        </govuk-radios>
      }

      <partial name="_SearchModelHiddenInputs" model="@Model.Data" />
      <input asp-for="Data.HasSingleSchool" type="hidden" />
      <input asp-for="Data.SchoolPostcode" type="hidden" />
      <input type="hidden" name="handler" value="Submit" />
      <div class="govuk-button-group">
        <govuk-button prevent-double-click="true" type="submit">Continue</govuk-button>
      </div>
      @if(!Model.Data.HasSingleSchool)
      {
        <a class="govuk-link govuk-body" href="/enquiry/build/school-postcode?@backQueryString">I need to choose another school</a>
      }
    </form>
  </div>
</div>

UI/Pages/Enquiry/Build/EmailVerification.cshtml
@page
@model EmailVerification
@using GovUk.Frontend.AspNetCore.TagHelpers
@{
  ViewData["Title"] = "Check your email";
  ViewData["BackLinkHref"] = $"/enquiry/build/enquirer-email?{Model.Data.ToQueryString()}";
}

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <form method="post">
      @if (!string.IsNullOrWhiteSpace(Model.Data.NewPasscodeSentAt))
      {
        <div aria-labelledby="govuk-notification-success-banner-title" class="govuk-notification-banner--success govuk-notification-banner" data-module="govuk-notification-banner" role="alert">
          <div class="govuk-notification-banner__header">
            <h2 class="govuk-notification-banner__title" id="govuk-notification-success-banner-title">Success</h2>
          </div>
          <div class="govuk-notification-banner__content">
            <p class="govuk-notification-banner__heading">
              We sent you a new passcode at @Model.Data.NewPasscodeSentAt
            </p>
          </div>
        </div>
      }
      <h1 class="govuk-heading-l">Check your email</h1>
      <p class="govuk-body">We sent a @UI.Constants.IntegerConstants.EmailVerificationPasscodeLength-digit passcode to @Model.Data.Email. It will expire in @UI.Constants.DoubleConstants.SessionTimeoutInMinutes minutes.</p>
      <div asp-validation-group-for="Data.Passcode">
        <govuk-input asp-for="Data.Passcode" input-class="govuk-input--width-10" spellcheck="false">
          <govuk-input-label>Enter passcode</govuk-input-label>
        </govuk-input>
      </div>
      <partial name="_SearchModelHiddenInputs" model="@Model.Data" />
      <input type="hidden" name="handler" value="Submit" />
      <div class="govuk-button-group">
        <govuk-button prevent-double-click="true" type="submit" data-testid="call-to-action">Continue</govuk-button>
      </div>
      <govuk-details>
        <govuk-details-summary>
          I have not received my passcode
        </govuk-details-summary>
        <govuk-details-text>
          <p class="govuk-body">If your passcode hasn’t arrived after 10 minutes, check your spam or re-enter your email address and try again.</p>
          <p class="govuk-body">If your passcode has expired, you can request a new one.</p>
          <button class="govuk-button govuk-button--secondary" data-module="govuk-button" data-prevent-double-click="true" type="submit" asp-page-handler="newpasscode" asp-all-route-data="@Model.Data.ToRouteData()">Request a new passcode</button>
        </govuk-details-text>
      </govuk-details>
      @if (!string.IsNullOrEmpty(Model.Data.PasscodeForTesting))
      {
        <h2 class="govuk-heading-m">Test code</h2>
        <p class="govuk-body">
          NOTE: the following code is only displayed in the non-production websites for testing purposes...
        </p>
        <p class="govuk-body">
          Code: @Model.Data.PasscodeForTesting
        </p>
        <input asp-for="Data.PasscodeForTesting" type="hidden" />
      }
    </form>
  </div>
</div>

UI/Pages/Enquiry/Build/EnquirerEmail.cshtml
@page
@model EnquirerEmail
@using GovUk.Frontend.AspNetCore.TagHelpers
@{
  var backLink = Model.Data.From == ReferrerList.CheckYourAnswers ? "/enquiry/build/check-your-answers" : "/enquiry/build/confirm-school";
  ViewData["Title"] = "We need to verify your school email address";
  ViewData["BackLinkHref"] = $"{backLink}?{Model.Data.ToQueryString()}";
}

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <form method="post">
      <h1 class="govuk-heading-l">We need to verify your school email address</h1>
      <p class="govuk-body">We&rsquo;ll also use this email to notify you if you get a response from a tuition partner.</p>
      <p class="govuk-body">Tuition partners won&rsquo;t be able to see your email address.</p>
      <div asp-validation-group-for="Data.Email" data-testid="enquirer-email">
        <govuk-input asp-for="Data.Email" input-class="govuk-input govuk-!-width-three-quarters" autocomplete="email" data-testid="enquirer-email-input-box" type="email" spellcheck="false">
          <govuk-input-label>Enter your school email</govuk-input-label>
        </govuk-input>
      </div>
      <partial name="_SearchModelHiddenInputs" model="@Model.Data" />
      <input type="hidden" name="handler" value="Submit" />
      <div class="govuk-button-group">
        <govuk-button prevent-double-click="true" type="submit" data-testid="call-to-action">Continue</govuk-button>
      </div>
    </form>
  </div>
</div>